# Generated by Django 5.2.1 on 2025-05-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_search_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
